import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import Book from 'App/Models/Book'

export default class BookSeeder extends BaseSeeder {
  public async run() {
    await Book.createMany([
      {
        "id": 1616897993164,
        "slug": "i-wasnt-born-lucky",
        "title": "I Wasn’t Born Lucky",
        "description": "<p>“I wasn’t born a lucky person, I’m just too strong.”</p>\n<p>On his way home late in the evening, Xiao Li found a letter asking for help and inexplicably came to an unknown place. He had to finish the task given before he could succeed in returning to reality. In the legendary haunted school, Xiao Li looked at his companions’ task of ‘survive until dawn’ and then looked at the tasks displayed in his book:</p>\n<p>Tell me your name.</p>\n<p>Tell me what you like.</p>\n<p>Kiss me.</p>\n<p>Xiao Li: ????</p>\n<p>He was very confused and then refused.</p>",
        "cover": "http://localhost:3222/book/i-wasnt-born-lucky/cover/300.webp",
        "color": null,
        "banner": null,


        "chapters": 1,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2000,
        "language_id": 495,
        "status_id": 2,
        "author_id": 1,
        "artist_id": null,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616897994027,
        "slug": "transmigration-of-the-famous-cyber-star",
        "title": "Transmigration of the Famous Cyber Star",
        "description": "<p>Liu Man transmigrated from thousands of years ago to the modern world. Before she transmigrated, she was completely broke. After she transmigrated, she was still worried about her wealth. And so, for her to survive, she decided to start earning money by becoming a cyber star: trading and selling products, recording daily activities with her kittens, and showing off bits of her skills. One day she realized, that unconsciously, she had become one of the most famous celebrities.</p>",
        "cover": "http://localhost:3222/book/transmigration-of-the-famous-cyber-star/cover/600.webp",
        "color": null,
        "banner": null,


        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2000,
        "language_id": 495,
        "status_id": 2,
        "author_id": 2,
        "artist_id": null,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616897995145,
        "slug": "glory",
        "title": "Glory",
        "description": "<p>This novel is also known as [I was caught and brought back after using and tossing aside the Great Demon King of e-sports…]\n</p><p>Wei Xiao––the former rookie king of the league, now an accompanying player and tr*sh talk king, had a stupefied look on his face!</p>\n<p>Someone bought 10,000 games with him!</p>\n<p>200 yuan a game, for a neat and tidy total of two million yuan!</p>\n<p>Wei Xiao: “Boss, you didn’t miscount the zeroes, right?”</p>\n<p>“No.”</p>\n<p>“You want me to accompany you to play 10,000 games?”</p>\n<p>“Mm.”</p>\n<p>Wei Xiao was amazed. But just when he thought he’d encountered a generous fool and was having a good time deceiving and playing with them, he discovered the other party’s identity.</p>\n<p>This person actually turned out to be his previous captain, the one whose hands were tired from accepting too many championship trophies, the one who made everyone feel fear when they heard his name, the Great Demon King of the league, Lu Feng!</p>\n<p>Wei Xiao: “I’m sorry for disturbing you, goodbye!”</p>\n<p>Lu Feng picked up the little bastard who wanted to run, “Have you played around enough? Come back for training if you’ve played enough!”</p>\n<p>Later on, Wei Xiao became famous in a single game. The host interviewed him, “How would you evaluate God Lu?”</p>\n<p>Wei Xiao: “God Lu? Great technique, strong physical strength, and the most heaven-defying thing is his endurance!”</p>\n<p>Host: “???”</p>\n<p>How come the answer seemed to be a little strange?!</p>",
        "cover": "http://localhost:3222/book/glory/cover/1000.webp",
        "color": null,
        "banner": null,


        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 495,
        "status_id": 2,
        "author_id": 3,
        "artist_id": null,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616897996051,
        "slug": "rebirth-of-the-tyrants-pet-regent-prince-is-too-fierce",
        "title": "Rebirth of the Tyrant’s Pet: Regent Prince is too Fierce",
        "description": "<p>The servant looked at the grieving princess. “Your Highness, the Regent Prince sent your scholar&nbsp;fiancé to the Western Butcher’s daughter!”&nbsp;</p>\n<p>The princess gritted her teeth, speaking to her servant that it matters not as she has other suitors in line. Many days later, much to her dismay, the servant ran in a hurry. “Your Highness, the Regent Prince expressed his intention of becoming your suitor! All other men in line were sold to Gou Lan Red District!”</p>\n<p>The princess was distressed. She said to her servant it matters not. She’ll soon be married to Prince Fuma. Then the uneventful came. The servant once more ran to her, almost tripping in the process. “Your Highness, Prince Fuma was imprisoned at home! Meanwhile, there’s a red sedan chair waiting at your residence for your marriage! It was led by the Regent Prince!</p>\n<p>The princess was stunned. For a day such as this to come, it seemed impossible. This nothing but a sad story of a female boss crossing back in time to hold the thick thighs of the big boss. But while raising him, she was eaten in the process.</p>",
        "cover": "http://localhost:3222/book/rebirth-of-the-tyrants-pet-regent-prince-is-too-fierce/cover/450.webp",
        "color": null,
        "banner": null,


        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 495,
        "status_id": 2,
        "author_id": 4,
        "artist_id": null,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,

      },
      {
        "id": 1616897996920,
        "slug": "a-vip-as-soon-as-you-log-in",
        "title": "A VIP as Soon as You Log In",
        "description": "<p>The blacksmith Anvil created weapons alone in a ruined world.</p>\n<p>He came across a community, a hero universe, where there are heroes of every dimension.</p>\n<p>All the heroes wanted his weapons,</p>\n<p>All the monsters hated him,</p>\n<p>All the world blessed his existence</p>\n<p>however nobody prevented his death.</p>\n<p>Decades later, a dimensional invasion started on earth.</p>\n<p>Kang Shin-hyuk, a boy who can’t use mana inherited Anvil’s VIP ID and memories.</p>",
        "cover": "http://localhost:3222/book/a-vip-as-soon-as-you-log-in/cover/480.webp",
        "color": null,
        "banner": null,


        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2000,
        "language_id": 497,
        "status_id": 2,
        "author_id": 5,
        "artist_id": 1,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616897997699,
        "slug": "marked-by-a-tyrant-after-transmigrating",
        "title": "Marked by a Tyrant After Transmigrating",
        "description": "<p>Ye Shu transmigrated into the book he had just read and became the first cannon fodder minister who was brought down by the tyrannical male lead, suffering a death by a thousand cuts, turned into dust, that kind of thing.</p>\n<p>Ye Shu resolutely packed up and decided to abscond before this could happen. On the road, feeling that he had been drugged, he accosted someone for help.</p>\n<p>Who would have expected that he would wake up the next day with the tyrant smiling beside him. “Did you sleep well?”</p>\n<p>Ye Shu: “……”</p>\n<p>To survive, Ye Shu was forced to enter the palace as a consort, and henceforth, lived a harsh life of being ordered around and squeezed by the tyrant.</p>\n<p>When the tyrant annotated folding memorials[1], he refilled his tea and ground more ink.</p>\n<p>When the tyrant ate, he tested his dishes for hidden drugs.</p>\n<p>When the tyrant retired for the night, he was even responsible for warming his bed.</p>\n<p>It wasn’t until his belly started to grow that Ye Shu noticed that the book he had transmigrated into seemed to be a bit buggy……</p>\n<p>This f*cking world was actually ABO.</p>\n<p>He hadn’t been drugged, previously… That was the first differentiation period as he became a Kunjun!</p>\n<p>Tyrant: “This Qianjun’s rut period is coming, my beloved consort……”</p>\n<p>Ye Shu slammed the bedchamber’s door in front of the tyrant. “Heh, not a chance.”</p>\n<p>—</p>\n<p>Note: [1] Folding memorial – Memorials were an official communication to the Emperor of China. A “Folding Memorial”, for instance, was to be written on pages small enough for the emperor to hold them in his hand and read without being observed.</p>",
        "cover": "http://localhost:3222/book/marked-by-a-tyrant-after-transmigrating/cover/1200.webp",
        "color": null,
        "banner": null,


        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 495,
        "status_id": 2,
        "author_id": 6,
        "artist_id": null,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616897998395,
        "slug": "back-to-the-age-of-the-80s",
        "title": "Back To The Age Of The 80s",
        "description": "<p>Li Zheng, a former Cold Spring Harbor Laboratory researcher, professor at Huaqing University, and head of the National Drug Research Laboratory, died suddenly after staying up all night and woke up to find himself back in a small fishing village in 1982.</p>\n<p>His father had disappeared and his mother had run away from home, leaving his cheap half-sister to take care of him.</p>\n<p>Faced with this HARD mode of life, Li Zheng revealed a standard smile.</p>\n<p>No fear, no gold finger could compare to my almost Nobel Prize winning head.</p>",
        "cover": "http://localhost:3222/book/back-to-the-age-of-the-80s/cover/200.webp",
        "color": null,
        "banner": null,
        "release_year": null,

        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 495,
        "status_id": 2,
        "author_id": 7,
        "artist_id": null,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616897999267,
        "slug": "invincible",
        "title": "Invincible",
        "description": "<p>The strong are lonesome. Overcoming the loneliness pushes you to stand invincible at the top. </p>\n<p>Pro-disciple of the Shaolin Temple on Earth, Huang Xiaolong was reborn into a Martial Spirit world, carrying Hua Xia’s secret knowledge, the Body Metamorphose Scripture. In a Martial Spirit world, only those with Martial Spirit are able to train in battle qi and become a warrior. </p>\n<p>Huang Xiaolong – born with a heaven-defying rare Martial Spirit – was mistakenly taken for common variant Martial Spirit during the awakening ceremony conducted by the tribe and thus sidelined. However, Huang Xiaolong with his common “variant” Martial Spirit again, and again displayed unnatural talent, defeating geniuses, shocking the clan and the entire Martial Spirit World</p>",
        "cover": "http://localhost:3222/book/invincible/cover/187.webp",
        "color": null,
        "banner": null,
        "release_year": null,

        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 495,
        "status_id": 2,
        "author_id": 8,
        "artist_id": null,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898000155,
        "slug": "i-am-overlord",
        "title": "I Am Overlord",
        "description": "<p>Xiang Shaoyun is the young master of an influential and powerful sect and is blessed with an extreme latent talent in martial cultivation. From talent comes confidence, and from confidence comes a declaration to give all the so-called geniuses a head start of ten years before catching up to them.</p>\n<p>Ten years later, Xiang Shaoyun appears at a tiny sect of a tiny town. Betrayed and disgraced by his own sect, he is penniless and powerless, his cultivation level lower than his peers’ due to the ten-year vow. Now to reclaim the glory he once had, he must climb to the top from the very bottom.</p>\n<p>Witness and join Xiang Shaoyun’s adventure in his rise to glory.</p>",
        "cover": "http://localhost:3222/book/i-am-overlord/cover/591.webp",
        "color": null,
        "banner": null,
        "release_year": null,

        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 495,
        "status_id": 2,
        "author_id": 9,
        "artist_id": null,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898000916,
        "slug": "raising-a-fox-spirit-in-my-home",
        "title": "Raising a Fox Spirit in My Home",
        "description": "<p>What happens when an ordinary university student runs into a cute, coquettish little fox? What if the little fox is actually a Cultivator? What future awaits the university student after this fateful meeting? Is he heading towards the path of doom? Or is he heading towards ultimate greatness? Read on to find out! Join us and let us embark on an epic journey where we follow the twists and turns of this human-animal… *cough*… human-demon love story.</p>",
        "cover": "http://localhost:3222/book/raising-a-fox-spirit-in-my-home/cover/250.webp",
        "color": null,
        "banner": null,


        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 495,
        "status_id": 2,
        "author_id": 10,
        "artist_id": null,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898002000,
        "slug": "i-favor-the-villainess",
        "title": "I Favor the Villainess",
        "description": "<p>“I am the heroine of an otome game, so is it wrong to like the villainess?”</p>\n<p>Corporate s*ave OL, Oohashi Rei, reincarnated as the heroine Rei Taylor in the world of the otome game 「Revolution」.</p>\n<p>Her preference isn’t the capturable princes, it’s the villainess, Claire François.</p>\n<p>She merrily accepts Claire’s dislike.</p>\n<p>With the protagonist’s involvement, it’s the beginning of a unique romcom.</p>\n<p>To make it worse, Rei’s love became directed at the villainess, what does Claire’s future hold?</p>\n<p>It’s my second series with a screwball villainess.</p>\n<p>A little different from ordinary… I hope you can enjoy the villainess who’s just a little different.</p>",
        "cover": "http://localhost:3222/book/i-favor-the-villainess/cover/600.webp",
        "color": null,
        "banner": null,


        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 496,
        "status_id": 2,
        "author_id": 11,
        "artist_id": 2,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898003032,
        "slug": "chu-wang-fei",
        "title": "Chu Wang Fei",
        "description": "<p>She, the prime minister’s daughter, was timid and cowardly. Because her engagement fell through, and her reputation was ruined, she was pressured to spill her own blood in the palace hall! Once again opening her eyes, the cowardice had vanished, replaced by coldness, causing others to be intimidated at first glance. Yet no one realized, she was not her.</p>\n<p>He, the current dynasty’s Chu Wang, served the country and brought peace and stability. Peerless and magnificent, all the girls under the Heavens eagerly pursued him! He helped her break off her engagement in the palace hall, but she avoided him at a great distance. He set his mind to pursue her, but she didn’t intend to love him.</p>\n<p>At home, the turbulent currents of government affairs surged violently, disputes from every country continued to spring up everywhere. The stunning her who had been reborn, and how she didn’t bat an eyelid to resolve that terrifying carnage; her name had shaken the whole world!</p>\n<p>When the dust had settled, and the song and dance had ceased, who could hold hands with her and look upon this thousand-year golden age, this flourishing ten thousand miles? Nowadays in this land under the Heavens, everyone spoke of how Chu Wang was cunning and two-faced, he desired the whole world, and was someone they seriously could not provoke. Yet the one they could not provoke even more was his Wang Fei – Yun Qian Meng! Anyone who provoked Chu Wang Fei, must surely be prepared to lose their necks!</p>\n<p>A breathtaking rebirth, a thrilling marriage, in the blink of an eye the once weak woman had become the honorable Chu Wang Fei!</p>\n<p>Wang Fei: In the palace chambers, between the feasts, smiles are hiding daggers, with layers and layers of plots and machinations; those who hurt my flesh and blood will have to pay the price.</p>\n<p>Chu Wang: In these troubled times, carrying the fire beacon, over thousands of miles of fortresses and mountains, I have traveled to the distance to these border stations; if you dare to hurt my wife I will take your life.</p>\n<p>Wang Fei: In another country, in a foreign land, will his thoughts stay pure? The princess of another nation is graceful and beautiful, will “a pair of people for one life” change?</p>\n<p>Chu Wang: Returning home, difficult problems arise. As green hills extend into the distance, beautiful flowers and tender feelings grow deeply; dealing with the ruler and his ministers is harder than rising into Heaven.</p>\n<p>That night, all the monarchs struggled for power, smoke rising all around; that night, the husband and wife were separated, neither humble nor haughty; that night, the land was in great disorder, lying corpses filled the plains; that night, whose heart was confused, whose family was broken, whose country was lost?</p>\n<p>In the chaos of war, during their separation, separated by thousands of miles of unmoving mountains and rivers, the gentleman’s heart and the wife’s heart never changed. In the lonely city without aid, hand in hand as before, they advanced together while chatting lightly about this West Chu country.</p>",
        "cover": "http://localhost:3222/book/chu-wang-fei/cover/240.webp",
        "color": null,
        "banner": null,
        "release_year": null,

        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 495,
        "status_id": 2,
        "author_id": 12,
        "artist_id": null,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898003900,
        "slug": "i-became-the-male-leads-sister",
        "title": "I Became the Male Lead’s Sister",
        "description": "<p>Evangeline, who was reincarnated as the male lead’s younger sister, only had one year left to live. While her lovestruck pathetic brother followed the heroine to the ends of the earth, she decided to find the man of destiny who could save her.&nbsp;&nbsp;The only clue Evangeline was given was that he was blonde. With a plan in mind, she snuck out the mansion in anticipation of finding him.&nbsp;But somehow, things began to move strangely. Instead of fate, she kept running into a brown-haired boy who smelled fishy.</p>\n<p>“Will you take responsibility for my first time?” he said.</p>\n<p>He was too handsome to be a supporting character, Evangeline thought. Was he the emperor? Or a crook? There’s no way the author would give such beauty to a supporting character of a novel. He’s definitely the other male lead… the emperor.</p>\n<p>“Are you the emperor?” Evangeline asked with confidence.</p>\n<p>“…No.”</p>\n<p>If not, then nevermind… but why was he so dazzling? While agonizing in such thought, she was swept away by him.</p>\n<p>“Wait, I don’t think I can. This feels weird.”</p>\n<p>“Is it strange to feel good?”</p>\n<p>“It’s weird.”</p>\n<p>“Why don’t you like it when you feel good? Can’t you just keep feeling good?”</p>\n<p>Nevermind. She decided to rest in peace. She wasn’t interested in magic, nor men, nor did she want to recover the memories she’s lost. Just… let her die comfortably! But… this annoying man keeps involving himself with her… even brought a dog leash…</p>",
        "cover": "http://localhost:3222/book/i-became-the-male-leads-sister/cover/787.webp",
        "color": null,
        "banner": null,


        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 497,
        "status_id": 2,
        "author_id": 13,
        "artist_id": 3,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898004976,
        "slug": "jubo",
        "title": "Jubo",
        "description": "<p>Wang Cheng: Boss Chu, I think my mom will not agree two hundred percent with our affair, so I have a once-and-for-all proposal, do you want to hear it?</p>\n<p>Chu Yifeng: Let’s hear it.</p>\n<p>Wang Cheng: It’s very simple, why don’t we break up and not worry about anything?</p>\n<p>Chu Yifeng: What you said is quite reasonable, but we can discuss this matter further in the bedroom.</p>\n<p>Wang Cheng: …I’m just kidding. Look at my sincere face. How could I break up with you?</p>\n<p>Chu Yifeng: It’s too late.</p>",
        "cover": "http://localhost:3222/book/jubo/cover/243.webp",
        "color": null,
        "banner": null,


        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 495,
        "status_id": 2,
        "author_id": 14,
        "artist_id": null,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898005973,
        "slug": "heavens-devourer",
        "title": "Heaven’s Devourer",
        "description": "<p>The Yanhuang Ancient Domain, vast without end, gave birth to many Celestials and Demons of antiquity tore Heaven and Earth apart and surpassed the control of the 3 Realms and 5 Elements over the endless years it has existed. Numerous Gods, more than ten thousand races, and humans born with a God class body have also come out from the Domain, traveling through the nether, warping Yin and Yang, omnipotent.</p>\n<p>In this current age, Celestial Daoism is in prosperity, tens of thousands of Divine techniques shake the Heavens, numerous mortals strive to become Celestials, and millions of sinners walk the Earth. The Prince Heir of the kingdom East Yue Wu Wu Yu, obtains the legacy of the Battle Celestial of the East in the direst of situations to sweep across the Earth and rebel against the Heavens!</p>\n<p>In the eyes of the hundreds of millions of Mortals, he is the Sovereign Emperor Celestial, overcoming a plethora of tribulations to reach his current height.</p>\n<p>In the eyes of the Celestials and Buddhas of Heaven, he is a peerless Heaven devouring Demon!</p>",
        "cover": "http://localhost:3222/book/heavens-devourer/cover/199.webp",
        "color": null,
        "banner": null,


        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 495,
        "status_id": 2,
        "author_id": 15,
        "artist_id": null,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898006853,
        "slug": "saye",
        "title": "SAYE",
        "description": "<p>When Jiang Cheng was told to return to a family that he never knew or had a relationship with, he had never expected to end up meeting a young girl, and eventually, her seemingly roguish brother Gu Fei, as a first encounter in the new city.</p>",
        "cover": "http://localhost:3222/book/saye/cover/618.webp",
        "color": null,
        "banner": null,


        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 495,
        "status_id": 2,
        "author_id": 16,
        "artist_id": null,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898008184,
        "slug": "martial-god-asura",
        "title": "Martial God Asura",
        "description": "<p>One night a mysterious and unexplained phenomenon occurs in the nine provinces. Five years later Chu Feng, a regular outer disciple of the Azure Dragon school, awakens one of the mysterious nine lightning beasts. And discovers an egg sealed inside him. </p>\n<p>From there we follow Chu Feng on his path of cultivation.</p>",
        "cover": "http://localhost:3222/book/martial-god-asura/cover/352.webp",
        "color": null,
        "banner": null,


        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 495,
        "status_id": 2,
        "author_id": 17,
        "artist_id": null,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898009162,
        "slug": "the-second-coming-of-gluttony",
        "title": "The Second Coming of Gluttony",
        "description": "<p>“The son of god Gula has returned.”</p>\n<p>I was lost in the world of gambling.</p>\n<p>I turned my back on my family and even betrayed my lover.</p>\n<p>I wasted every day of my life.</p>\n<p>It was a life of tr*sh.</p>\n<p>The reality told me thus:</p>\n<p>That I would amount to nothing no matter what I did.</p>\n<p>In order to change my pathetic life, I chose fantasy, instead.</p>\n<p>Even then, it was the same story.</p>\n<p>I wondered if salvation would come at the end of the long road.</p>\n<p>But, I was forced to kneel down in defeat in front of a powerful entity.</p>\n<p>The tower I built up with my own hands crumbled into nothingness.</p>\n<p>Just for once, I dearly wished to know the truth about myself.</p>\n<p>“Come closer, my child…”</p>\n<p>I will not hold back this time.</p>",
        "cover": "http://localhost:3222/book/the-second-coming-of-gluttony/cover/500.webp",
        "color": null,
        "banner": null,


        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 497,
        "status_id": 2,
        "author_id": 18,
        "artist_id": null,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898010017,
        "slug": "clearing-an-isekai-with-the-zero-believers-goddess-the-weakest-mage-among-the-classmates",
        "title": "Clearing an Isekai with the Zero-Believers Goddess – The Weakest Mage among the Classmates (WN)",
        "description": "<p>“Your stats are lower than that of your average person.”</p>\n<p>The weakest by a mile among the otherworldlers of class 1-A, Takatsuki Makoto.</p>\n<p>The Heroes and Sages who had cheat skills in his class had went off, and the base set lifespan is 10 years?</p>\n<p>The Great Demon Lord is going to revive soon?</p>\n<p>I am a Mage Apprentice?</p>\n<p>Isn’t the balance way too bad? This damn Isekai is a tr*sh game!</p>\n<p>“Want to be my believer?”, the Goddess that told me this has zero believers!</p>\n<p>Aah, this is bad…I don’t think I can clear this. The Goddess with zero believers is an incredible beauty, and she is telling me she is imprisoned somewhere and is waiting to be saved. My last and hardest mission is to save the Goddess.</p>\n<p>Clearing this Isekai that only has adversities, the story of the weakest mage.</p>",
        "cover": "http://localhost:3222/book/clearing-an-isekai-with-the-zero-believers-goddess-the-weakest-mage-among-the-classmates/cover/600.webp",
        "color": null,
        "banner": null,


        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 496,
        "status_id": 2,
        "author_id": 19,
        "artist_id": 4,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898011104,
        "slug": "trash-of-the-counts-family",
        "title": "Trash of the Count’s Family",
        "description": "<p>When I opened my eyes, I was inside a novel.</p>\n[The Birth of a Hero].<p></p>\n[The Birth of a Hero] was a novel focused on the adventures of the main character, Choi Han, a high school boy who was transported to a different dimension from Earth, along with the birth of the numerous heroes of the continent.<p></p>\n<p>I became a part of that novel as the tr*sh of the Count’s family, the family that oversaw the territory where the first village that Choi Han visits is located.</p>\n<p>The problem is that Choi Han becomes twisted after that village, and everyone in it, are destroyed by assassins.</p>\n<p>The bigger problem is the fact that this s*upid tr*sh who I’ve become doesn’t know about what happened in the village and messes with Choi Han, only to get beaten to a pulp.</p>\n<p>“…This is going to be a problem.”</p>\n<p>I feel like something serious has happened to me.</p>\n<p>But it was worth trying to make this my new life.</p>",
        "cover": "http://localhost:3222/book/trash-of-the-counts-family/cover/460.webp",
        "color": null,
        "banner": null,


        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 497,
        "status_id": 2,
        "author_id": 20,
        "artist_id": 5,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898012246,
        "slug": "tsuki-ga-michibiku-isekai-douchuu",
        "title": "Tsuki ga Michibiku Isekai Douchuu",
        "description": "<p>High school student Misumi Makoto is called into a fantasy world by the god Tsukuyomi, in order to be a hero. However, the Goddess ruling the world isn’t as thrilled to have him there, and kicks him to the edge of the world. Tsukuyomi declares that Makoto is free to find his own way after Makoto is abandoned by the other Goddess.</p>",
        "cover": "http://localhost:3222/book/tsuki-ga-michibiku-isekai-douchuu/cover/504.webp",
        "color": null,
        "banner": null,


        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 496,
        "status_id": 2,
        "author_id": 21,
        "artist_id": 6,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898013015,
        "slug": "the-undetectable-strongest-job-rule-breaker",
        "title": "The Undetectable Strongest Job: Rule Breaker",
        "description": "<p>By some ill fortune, Hikaru died in a traffic accident. He was in heaven standing in line, waiting to be judged, when he took an unexpected request to transfer his soul to a person in another world. He received an ability called Soul Board which he could use to allocate points to Skills to make himself more powerful.</p>\n<p>But there was a catch…</p>\n<p>「I want you to take revenge on someone for me  within an hour. If you don’t, I’ll destroy your soul.」</p>\n<p>To pull off the task assigned to him, he poured all his available points to the Stealth skill tree.</p>\n<p>This is a story of a boy who specialized in Stealth. With his skill trees as weapons, he would demonstrate his unrivaled strength in another world.</p>",
        "cover": "http://localhost:3222/book/the-undetectable-strongest-job-rule-breaker/cover/725.webp",
        "color": null,
        "banner": null,


        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 496,
        "status_id": 2,
        "author_id": 22,
        "artist_id": 7,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898013913,
        "slug": "the-man-picked-up-by-the-gods-reboot",
        "title": "The Man Picked Up By the Gods (Reboot)",
        "description": "<p>Takebayashi Ryouma, a 39 years old man with hidden past, found himself in a strange white room. The gods tell him that he has died and that they are sending his soul to a different world, a world where magic exists. After living alone for 3 years, his gamer soul loses its common sense and starts along crazy routes.</p>",
        "cover": "http://localhost:3222/book/the-man-picked-up-by-the-gods-reboot/cover/600.webp",
        "color": null,
        "banner": null,


        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 496,
        "status_id": 2,
        "author_id": 23,
        "artist_id": 8,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898015017,
        "slug": "the-strongest-dull-princes-secret-battle-for-the-throne",
        "title": "The Strongest Dull Prince’s Secret Battle for the Throne",
        "description": "<p>The Adrasia empire on the Vogel continent. There is a battle over the throne of such an empire that possesses powerful military and vast territory.</p>\n<p>With the successor undecided, the children of the emperor are vying to expand their power. However, there was one prince that everyone says will definitely not become the emperor.</p>\n<p>The seventh prince, Arnold Lakes Adler. The young man who was inferior to his younger twin brother in every way, the dull prince.</p>\n<p>Incompetent and lethargic, Arnold wastes everyday just playing around. However, behind the scenes, he is one of the only five SS-Class adventurers called ‘Silver’.</p>\n<p>Seeing the intensifying battle for the throne he decided “I don’t want to die so let’s have my little brother become the emperor…”</p>\n<p>This is the tale of absurd secret manoeuvres of the prince who is uninterested in the title of the emperor.</p>",
        "cover": "http://localhost:3222/book/the-strongest-dull-princes-secret-battle-for-the-throne/cover/705.webp",
        "color": null,
        "banner": null,


        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 496,
        "status_id": 2,
        "author_id": 24,
        "artist_id": 9,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898015890,
        "slug": "ending-maker",
        "title": "Ending Maker",
        "description": "<p>Two heroes of the game Legend of Heroes 2 that were rotten water*.</p>\n<p>Kang Jin-ho in the first place and Hong Yoo Hee in the second place.</p>\n<p>One day, I opened my eyes and reincarnated as a character in the game…</p>\n<p>“Hey…you too?”</p>\n<p>“Hey…me too!”</p>\n<p>The ending of Legend of Heroes 2 is the destruction of the human world.</p>\n<p>But if there’s two of us and we’re not alone.</p>\n<p>If it is also the #1 and #2 in the server rankings.</p>\n<p>The path of rotten water begins for a perfect happy ending!</p>\n<p>(*Rotten water is Korean slang for someone who has played a certain game for a long time and mastered everything. Think of them as oldbies, veterans, or game pros.)</p>",
        "cover": "http://localhost:3222/book/ending-maker/cover/480.webp",
        "color": null,
        "banner": null,


        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 497,
        "status_id": 2,
        "author_id": 25,
        "artist_id": 1,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898016881,
        "slug": "emperors-domination",
        "title": "Emperor’s Domination",
        "description": "<p>A boy that was imprisoned for millions of years has regained a mortal body.</p>\n<p>He became a disciple of the declining Cleansing Incense Ancient Sect where its patriarch used to be his disciple. Now he will bring this sect back to its former glory.</p>\n<p>This is his journey to reach the apex and take revenge on those who had imprisoned him.</p>\n<p>This is his story of meeting old friends and making new companions.</p>\n<p>This is his path of traversing the Nine Worlds and becoming the next ruler of the Heavens.</p>\n<p>Several millennia have passed and the golden age of experts have passed. A master whose disciples once were the most exalted Immortals among the 9 worlds has all left him. With his mortal body, mortal physique and mortal life wheel… he shall sweep the 9 worlds and take what is rightfully his.</p>",
        "cover": "http://localhost:3222/book/emperors-domination/cover/306.webp",
        "color": null,
        "banner": null,


        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 495,
        "status_id": 2,
        "author_id": 26,
        "artist_id": null,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898017688,
        "slug": "never-die-extra",
        "title": "Never Die Extra",
        "description": "<p>Extras die every day in various ways in the game [Yo-Ma Great War 3].</p>\n<p>He was an extra when he reincarnated into the game.</p>\n<p>I’ll never die. Never.</p>\n<p>“Let’s get started.”</p>\n<p>Evan had come to a conclusion. He tapped his cheeks as a way of signaling to himself that he had made up his mind.</p>\n<p>He would become a character who never dies.</p>",
        "cover": "http://localhost:3222/book/never-die-extra/cover/750.webp",
        "color": null,
        "banner": null,


        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 497,
        "status_id": 2,
        "author_id": 5,
        "artist_id": 1,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898018841,
        "slug": "i-became-the-wife-of-the-monstrous-crown-prince",
        "title": "I Became the Wife of the Monstrous Crown Prince",
        "description": "<p>She transmigrated into the body of Ancia, the current wife of the monstrous crown prince, Blake, in an R-19 romance novel.</p>\n<p>In the original story, Ancia committed suicide on the day of their marriage, leaving Blake with massive trauma. But this time, Ancia wouldn’t do such a thing.</p>\n<p>Blake was the second male lead in the original novel. He was portrayed as a beast that possessed an exquisite facade. Yet, right now, he was behaving just like an innocent rabbit.</p>\n<p>The only person who can remove the crown prince’s curse is the heroine, Diana. My role is to just keep this little boy from getting hurt and then step down in time, but…..</p>\n<p>“Ancia, don’t leave me!”</p>\n<p>This little rabbit keeps chasing me.</p>",
        "cover": "http://localhost:3222/book/i-became-the-wife-of-the-monstrous-crown-prince/cover/881.webp",
        "color": null,
        "banner": null,


        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 497,
        "status_id": 2,
        "author_id": 27,
        "artist_id": 10,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898019495,
        "slug": "moons-labyrinth",
        "title": "Moon’s Labyrinth",
        "description": "<p>His friend and his wife betrayed him. The only thing left to him was his massive debt and his precious daughter. He was without hope as he lived at the bottom. However, a last chance had come to Sungyoon. He was a ‘man without a heartbeat’, and he will explore the Moon’s Labyrinth. He’ll explore the parts of the dungeon yet to be seen!</p>",
        "cover": "http://localhost:3222/book/moons-labyrinth/cover/208.webp",
        "color": null,
        "banner": null,


        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 497,
        "status_id": 2,
        "author_id": 28,
        "artist_id": null,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898020291,
        "slug": "otonari-no-tenshi-sama-ni-itsu-no-ma-ni-ka-dame-ningen-ni-sareteita-ken-wn",
        "title": "Otonari no Tenshi-sama ni Itsu no Ma ni ka Dame Ningen ni Sareteita Ken (WN)",
        "description": "<p>Amane Fujimiya’s neighbour in the apartment he lives in is the school’s number one lovable angel: Excellent and with a level of beauty that can only be described as angelic – Mahiru Shiina. Amane, an ordinary student who doesn’t stand out, is her neighbour, but until now, they didn’t interact with each other. After meeting the soggy angel in the rain:</p>\n<p>“I’m returning what I borrowed. By the way, clean up your room. It’s filthy.”</p>\n<p>“None of your business.”</p>\n<p>A relationship with a sharp-tongued angel begins, starting with handing over an umbrella. From catching a cold and having someone take care of you, to making a meal for someone because they neglected their health, to joint work (cleaning rooms)…</p>",
        "cover": "http://localhost:3222/book/otonari-no-tenshi-sama-ni-itsu-no-ma-ni-ka-dame-ningen-ni-sareteita-ken-wn/cover/1000.webp",
        "color": null,
        "banner": null,


        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 496,
        "status_id": 2,
        "author_id": 29,
        "artist_id": 11,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898021471,
        "slug": "the-villainess-female-supporting-character-raising-her-bun",
        "title": "The Villainess Female Supporting Character Raising Her Bun",
        "description": "<p>Cheng Huan woke up and had transmigrated as the villainess female supporting character in a novel.</p>\n<p>The female supporting character was very money-loving and used her own son as a chip to try and get into a prestige family. Finally, the child died in an accident and the female supporting character also met her tragic fate.</p>\n<p>Cheng Huan, who had been single her entire life, looked at the teary-eyed little boy next to her, let out a sigh of relief, and picked up the heavy burden of being a mother.</p>\n<p>As the days went on by, the legendary child’s father showed up spontaneously!</p>\n<p>Cheng Huan: I really don’t want to be the third wheel in your relationship!!</p>\n<p>The spontaneously-appeared male lead: ….but there is nobody else.</p>",
        "cover": "http://localhost:3222/book/the-villainess-female-supporting-character-raising-her-bun/cover/471.webp",
        "color": null,
        "banner": null,


        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 495,
        "status_id": 2,
        "author_id": 30,
        "artist_id": null,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898022420,
        "slug": "im-the-evil-lord-of-an-intergalactic-empire",
        "title": "I’m the Evil Lord of an Intergalactic Empire!",
        "description": "<p>Liam Sera Banfield is a reincarnator.</p>\n<p>He was reincarnated into a fantasy universe of swords and magic, but at a time that civilization was already making advancements into outer space.</p>\n<p>The setting takes place in an intergalactic empire, a space opera-like universe where humanoid weapons and spaceships do battle.</p>\n<p>Liam, who had incarnated into an aristocratic family in a monarchic society, has the ambition to one day become an evil lord.</p>\n<p>In his previous life, Liam had unfortunately lost everything and died in despair.</p>\n<p>— It’s foolish to live for others.</p>\n<p>— I will live for myself.</p>\n<p>Holding those feelings in his chest, he starts towards his second life, but is instead worshipped as a virtuous ruler from his difference in values.</p>\n<p>Will Liam be able to safely become an evil lord? </p>",
        "cover": "http://localhost:3222/book/im-the-evil-lord-of-an-intergalactic-empire/cover/1447.webp",
        "color": null,
        "banner": null,


        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 496,
        "status_id": 2,
        "author_id": 31,
        "artist_id": 12,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898023383,
        "slug": "kochugunshikan-boukensha-ni-naru",
        "title": "Kochugunshikan Boukensha ni Naru",
        "description": "<p>Imperial Galactic Army Officer Alan Corinth’s ship is seriously damaged after being ambushed by an unknown foe in hyperspace.</p>\n<p>Even though it was through sheer coincidence, he became the sole survivor.</p>\n<p>The stricken ship fell to the planet below.</p>\n<p>Alan alone managed to get to an escape pod.</p>\n<p>Alan the Imperial Army Officer wagers his survival in this savage world on the symbiotic nanomachines (nanom) in his body.</p>\n<p>The world he landed on was home to a prosperous human civilization, which seemed to have a strangely similar genetic pedigree to himself.</p>\n<p>In this puzzling fantasy world of swords and sorcery, Alan will live to the fullest alongside his comrades.</p>\n<p>What will Alan achieve in this strange world?</p>\n<p>A Science Fiction Fantasy in a Middle Ages setting starts here.</p>",
        "cover": "http://localhost:3222/book/kochugunshikan-boukensha-ni-naru/cover/843.webp",
        "color": null,
        "banner": null,


        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 496,
        "status_id": 2,
        "author_id": 32,
        "artist_id": 13,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898024275,
        "slug": "after-transmigrating-into-a-short-lived-white-moonlight-had-a-he-with-the-villain",
        "title": "After Transmigrating into a Short-lived White Moonlight, had a HE with the Villain",
        "description": "<p>Sang Yuanyuan transmigrated into a sadistic romance ancient fantasy novel, becoming the male lead’s ill-fated beautiful white moonlight that died early.</p>\n<p>The male lead loves her, the male supporting character loves her too.</p>\n<p>The female lead was injured and broken-hearted because being loved, trampled and abused by all men for she had a face that was similar to hers. The relationship with male lead was full of twists and turns, tortured between life and death, and finally had a Happy Ending.</p>\n<p>Sang Yuanyuan : “ I’m sorry, I 一 first don’t want to die, second don’t want to be abused. So I choose to run away with the villain. Excuse me, goodbye.”</p>\n<p>The villain squinted his long eyes, with a lazy posture and lips smiling like a spring breeze——</p>\n<p>“Beside me….is nothing but hell.”</p>\n<p>She contemplated for three seconds.</p>\n<p>“Does the hell have land?”</p>\n<p>“….. there’s a wasteland.”</p>\n<p>“Does it have water?”</p>\n<p>“…… only blood.”</p>\n<p>He wants to see her panic and lose her head, waits for her to scream and escape, but after blanking for three seconds the woman’s eyes instead shine faintly.</p>\n<p>“What a good opportunity to try a new variety!”</p>\n<p>“……”</p>\n<p>He who always lingers in the deepest darkness, has never thought that there would be a person who can fill a whole wasteland with flowers and grasses.</p>",
        "cover": "http://localhost:3222/book/after-transmigrating-into-a-short-lived-white-moonlight-had-a-he-with-the-villain/cover/600.webp",
        "color": null,
        "banner": null,


        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 495,
        "status_id": 2,
        "author_id": 33,
        "artist_id": null,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898025510,
        "slug": "shinka-no-mi",
        "title": "Shinka no Mi",
        "description": "<p>A class full of idols and beautiful people are sent to another world. However there is one guy who is ugly, fat and smells… our protagonist. This is his comedic story of evolution and the slow building of his harem. The first heroine is a gorilla.</p>",
        "cover": "http://localhost:3222/book/shinka-no-mi/cover/463.webp",
        "color": null,
        "banner": null,


        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 496,
        "status_id": 2,
        "author_id": 34,
        "artist_id": 14,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898026375,
        "slug": "not-sure-but-it-looks-like-i-got-reincarnated-in-another-world",
        "title": "Not Sure, But It Looks Like I Got Reincarnated in Another World",
        "description": "<p>Ren, a ten year old orphan girl, was en route to being delivered to a corrupt merchant. However, bandits attacked the carriage she was on and caused it to plummet down the sides of a cliff. But the impact from the accident awoken her memories from a past life. She was from a world called Earth, and was once a male researcher in his mid-thirties who had died in an explosion resulting from an experiment gone awry. According to her memories for the past ten years, she had reincarnated in another world after dying and grew up in an orphanage. In order to escape a future where she would be ens*aved by the merchant, Ren will draw upon the knowledge from her past life and magic aptitude for all elements, to create new forms of magic and survive in a harsh, new world alone.</p>",
        "cover": "http://localhost:3222/book/not-sure-but-it-looks-like-i-got-reincarnated-in-another-world/cover/1440.webp",
        "color": null,
        "banner": null,


        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 496,
        "status_id": 2,
        "author_id": 35,
        "artist_id": 15,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898027631,
        "slug": "the-male-leads-villainess-stepmother",
        "title": "The Male Lead’s Villainess Stepmother",
        "description": "<p>Yan Shuyu, a big fan of all sorts of cliche CEO novels, had transmigrated into a book —</p>\n<p>In the novel, the wealthy CEO male lead has a villainous stepmother. She put up a front of being nice and tender to him, when in fact she was bullying the male lead with her son. After she had successfully driven the male lead and his father apart, her ambition continued to grow as she attempted to take away the inheritance from the male lead. In the second half of the book, the truth came out — that the father had no feelings for her whatsoever but was merely using the two of them to hone his son’s character. In the end, both the stepmom and her son were sent to jail by the male lead after he took over the family business.</p>\n<p>Yan Shuyu transmigrated and became the well-hated villainous stepmother, but she had transmigrated to the time before everything happened, and the male lead was still a foolish child. Only a fool would want to become the stepmother of a foolish child. Yan Shuyu took a longing look at her “assigned husband”, who was pretty much like the Sleeping Beauty, before she quickly packed up and made a run for it.</p>\n<p>After that, Yan Shuyu checked out her $250 remaining on her card. She turned to look at her son, who was clinging onto her leg and asking for milk. She wanted to look up at the sky and howl. Is it too late to go back to become the male lead’s whetstone?</p>",
        "cover": "http://localhost:3222/book/the-male-leads-villainess-stepmother/cover/200.webp",
        "color": null,
        "banner": null,


        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 495,
        "status_id": 2,
        "author_id": 36,
        "artist_id": null,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898029189,
        "slug": "a-record-of-a-mortals-journey-to-immortality",
        "title": "A Record of a Mortal’s Journey to Immortality",
        "description": "<p> A poor and ordinary boy from a village joins a minor sect in Jiang Hu and becomes an Unofficial Disciple by chance. How will Han Li, a commoner by birth, establish a foothold for himself in his sect? With his mediocre aptitude, how will he successfully traverse the path of cultivation and become an immortal? </p>\n<p>This is a story of an ordinary mortal who, against all odds, clashes with devilish demons and the ancient celestials in order to find his own path to immortality. </p>\n<div class=\"yasr_schema\" itemscope=\"\" itemtype=\"http://schema.org/Review\"><span itemprop=\"itemReviewed\" itemscope=\"\" itemtype=\"http://schema.org/Product\">  <span itemprop=\"name\"> A Record of a Mortal’s Journey to Immortality </span></span><span itemprop=\"author\" itemscope=\"\" itemtype=\"http://schema.org/Person\"> reviewed by <span itemprop=\"name\">  </span></span> on <meta itemprop=\"datePublished\" content=\"2015-09-19T03:09:55+00:00\"> September 19, 2015<span itemprop=\"reviewRating\" itemscope=\"\" itemtype=\"http://schema.org/Rating\"> rated <span itemprop=\"ratingValue\">2.0</span> of <span itemprop=\"bestRating\"> 5 </span></span></div>",
        "cover": "http://localhost:3222/book/a-record-of-a-mortals-journey-to-immortality/cover/300.webp",
        "color": null,
        "banner": null,


        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 495,
        "status_id": 2,
        "author_id": 37,
        "artist_id": null,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898030105,
        "slug": "level-99-villainous-daughter",
        "title": "Level 99 Villainous Daughter",
        "description": "<p>I was reborn as the villainous daughter, Yumiela Dolknes, in the world of an otome RPG game. Yumiela only had a small role in the original story, but after defeating the Demon King, she will appear as the Hidden Boss with a bonus specs to solo fight the Hero party.</p>\n<p>Having a gamer-spirit, I’ve been raising my level since I was a child. By the time I enter the academy where the game stage is, I was level 99.</p>\n<p>I wanted the heroine and the capture targets to defeat the Demon King, but they just flirted around and didn’t raise their level. Moreover, they treat me as if I’m the Demon King just because I have dark hair and use dark magic.</p>\n<p>It’s a story where I aim for peaceful days.</p>",
        "cover": "http://localhost:3222/book/level-99-villainous-daughter/cover/675.webp",
        "color": null,
        "banner": null,


        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 496,
        "status_id": 2,
        "author_id": 38,
        "artist_id": 16,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898031068,
        "slug": "the-villain-and-the-cannon-fodders-mother",
        "title": "The Villain and the Cannon Fodder’s Mother",
        "description": "<p>Right after getting the first-class chef’s certificate and before that certificate had been in her hands long enough to warm up, she woke up. Not only did she age ten years, she also gained two children…</p>",
        "cover": "http://localhost:3222/book/the-villain-and-the-cannon-fodders-mother/cover/602.webp",
        "color": null,
        "banner": null,


        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 495,
        "status_id": 2,
        "author_id": 39,
        "artist_id": null,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898032035,
        "slug": "i-became-the-stepmother-of-my-ex-husband",
        "title": "I Became The Stepmother of My Ex-husband",
        "description": "<p>Lin Wei Xi found out after she died that she was just a cannon fodder in a novel, used as contrast to the gentle and considerate and virtuous female lead.</p>\n<p>The male lead was her ex-husband, the dignified heir of Yan Wang, his family were superior and brilliant, but the heroine was not her.</p>\n<p>The female lead was her concubine-born younger sister, and her husband’s white moonlight, his cinnabar mole, no wonder! After Lin Wei Xi died, her husband finally married her sister as he wished. </p>\n<p>She watched coldly at the two like honey in the oil, in love and harmonious, everyone using the success of her younger sister to contrast the impropriety of the original wife.</p>\n<p>Lin Wei Xi sneered, okay, since your love moves the world, then this sister will come back and be your stepmother! </p>\n<p>So she married her ex-husband’s father, the father-in-law she never met in the previous life, the country’s God of war, who has not remarried after losing his wife, the one that hold military power, the brilliant Yan Wang.</p>\n<p>Later Yan Wang, who was in his prime years and used to act decisively, looked at his small, delicate, much younger wife, and had a headache.</p>\n<p>No matter, she is still young, he have to spoil her, indulge her, teach her.</p>",
        "cover": "http://localhost:3222/book/i-became-the-stepmother-of-my-ex-husband/cover/400.webp",
        "color": null,
        "banner": null,


        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 495,
        "status_id": 2,
        "author_id": 40,
        "artist_id": null,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898032928,
        "slug": "how-to-tame-my-beastly-husband",
        "title": "How to Tame My Beastly Husband",
        "description": "<p>‘I’m sure I was……dead.’</p>\n<p>Annette Bavaria, a woman from the most prestigious noble family in the Deltium kingdom , returned back to the day of her wedding.</p>\n<p>The groom’s face was fierce as they entered the hall for the ceremony. He clutched her arm tightly because he hated Annette terribly.</p>\n<p>Now they were going to have a hellish marriage again, hurting each other.</p>\n<p>                                       ***</p>\n<p>“Don’t do this, Rafael.”</p>\n<p>“Shh, Annette. If you really want me to stop, please don’t open your dirty mouth. I’m going crazy right now because I want to squeeze it right in.”</p>\n<p>She looked at her husband tearing her clothes with tearful eyes.</p>\n<p>He was still horribly mean, arrogant, and a beast who only coveted her body.</p>\n<p>If she didn’t want to die again, she had to tame this wicked beast somehow.</p>\n<p>There was no other option.</p>",
        "cover": "http://localhost:3222/book/how-to-tame-my-beastly-husband/cover/450.webp",
        "color": null,
        "banner": null,


        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 497,
        "status_id": 2,
        "author_id": 41,
        "artist_id": 17,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898033704,
        "slug": "life-once-again",
        "title": "Life, Once Again!",
        "description": "<p>Sometimes, as we go about with our lives, we all happen to think of one specific thought at least once.</p>\n<p>What if… I could go back to “that” time?</p>\n<p>The funny thing is, the moment you think such a thought is the precise moment when you came back to the past, from the future.</p>\n<p>“One more time.”</p>\n<p>Life, once again.</p>",
        "cover": "http://localhost:3222/book/life-once-again/cover/480.webp",
        "color": null,
        "banner": null,
        "release_year": null,

        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 497,
        "status_id": 2,
        "author_id": 42,
        "artist_id": null,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898034730,
        "slug": "everyone-else-is-a-returnee",
        "title": "Everyone Else is a Returnee",
        "description": "<p>Left out during the elementary school picnic.</p>\n<p>Left out during the middle school camp.</p>\n<p>Left out during the high school trip.</p>\n<p>I finally became a college student, and what? I’m left out from all of humanity?</p>\n<p>Ignored by God, Yu IlHan spends a millennium sharpening his skills for the Great Cataclysm, watching over Earth alone while everybody else is away in other worlds.</p>\n<p>His legend starts after humanity comes back and meets the Great Cataclysm!</p>",
        "cover": "http://localhost:3222/book/everyone-else-is-a-returnee/cover/463.webp",
        "color": null,
        "banner": null,


        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 497,
        "status_id": 2,
        "author_id": 5,
        "artist_id": null,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898035598,
        "slug": "the-overlord-of-blood-and-iron",
        "title": "The Overlord of Blood and Iron",
        "description": "<p>The Overlord, Kang Chul-In. The man who was so strong that he had to be defeated. Having lost, he must now go back in time to take up the challenge of becoming The Emperor in the Continent of Pangaea. Will Kang Chul-In be able to overcome the 9 other Overlords in order to grasp the Continent of Pangaea within his hands?</p>",
        "cover": "http://localhost:3222/book/the-overlord-of-blood-and-iron/cover/480.webp",
        "color": null,
        "banner": null,


        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 497,
        "status_id": 2,
        "author_id": 43,
        "artist_id": null,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898036463,
        "slug": "demon-king",
        "title": "Demon King",
        "description": "<p>After dying, I woke up as a weak goblin. </p>\n<p>To survive, I have to destroy, consume, and evolve off of other monsters.</p>\n<p>From the ugly guy to the king who rules everything!</p>",
        "cover": "http://localhost:3222/book/demon-king/cover/477.webp",
        "color": null,
        "banner": null,


        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 497,
        "status_id": 2,
        "author_id": 5,
        "artist_id": 1,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898037397,
        "slug": "the-legitimate-daughter-doesnt-care",
        "title": "The Legitimate Daughter Doesn’t Care!",
        "description": "<p>There was a big scandal in the Mu family.</p>\n<p>The real daughter of the Mu family was switched by the nanny since she was a child. The Mu family didn’t bring her back from countryside until 17 years later!</p>\n<p>After the true daughter returned – There was no affection, only sympathy.</p>\n<p>The Mu family parents asked her, “We have a deep relationship with Yaoyao. We can’t let her lose face. We can only announce you as an adopted daughter to the outside world. You won’t blame us, right?”</p>\n<p>Her fiancée also said: “My fiancée can only be Yaoyao! Get out of here country bumpkin.”</p>\n<p>The attitude of her older brother Mu Qingyi was even more complicated.</p>\n<p>Yet despite all that, the real daughter, Xu Xinduo, said indifferently, “It doesn’t matter.”</p>\n<p>***</p>\n<p>From a young age Xu Xinduo could swap bodies with a certain teenager. That teenager would always exclaim in an annoyed tone, “Let’s switch bodies, I just don’t feel like taking piano lessons.</p>\n<p>Xu Xinduo helped the teenager to win various trophies, become a top student and honed his noble temperament and talent after taking over his body.</p>\n<p>***</p>\n<p>At a banquet, everyone in the Mu family watched as a rich young master strode towards Xu Xinduo and said, “Be my girlfriend, although you are from a small family… you are very beautiful.”</p>\n<p>With a smile Xu Xinduo replied, “I’m starting to miss my parents already.”</p>\n<p>Such a quick change of attitude?!</p>\n<p>The romantic story of the indifferent real daughter x a filthy rich despotic young master</p>\n<p>Note: Here “switching bodies” means swapping of souls. It’s temporary and doesn’t involve any physical changes.</p>",
        "cover": "http://localhost:3222/book/the-legitimate-daughter-doesnt-care/cover/400.webp",
        "color": null,
        "banner": null,


        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 495,
        "status_id": 2,
        "author_id": 44,
        "artist_id": null,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898038322,
        "slug": "everyone-knows-im-a-good-person",
        "title": "Everyone Knows I’m a Good Person",
        "description": "<p>Shi Qing’s task was to be a protector.</p>\n<p>It was only after transmigrating to various worlds and eagerly counterattacking the villains there that he realized he was the biggest villain out of everyone.</p>\n<p>– A King that liked to conquer other worlds</p>\n<p>– A Film Emperor that had a malicious personality</p>\n<p>– A Blackened Young Master with deviant intentions</p>\n<p>– A Schoolyard Bully that was overbearing to others</p>\n<p>Afterwards the gong that initially despised Shi Qing discovered:</p>\n<p>– The Machine King that seemed like an invader was really a million-year-old baby</p>\n<p>– The Film Emperor that seemed malicious was secretly helping upcoming actors</p>\n<p>– The Young Master that seemed to harbor deviant intentions was a pure-hearted young boy</p>\n<p>– The Schoolyard Bully that seemed overbearing was secretly in love</p>\n<p>In the end….</p>\n<p>The entire world: He’s such a good person!</p>",
        "cover": "http://localhost:3222/book/everyone-knows-im-a-good-person/cover/500.webp",
        "color": null,
        "banner": null,


        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 495,
        "status_id": 2,
        "author_id": 45,
        "artist_id": null,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898039400,
        "slug": "reincarnated-as-a-dragons-egg-lets-aim-to-be-the-strongest",
        "title": "Reincarnated as a Dragon’s Egg ～Lets Aim to Be the Strongest～",
        "description": "<p>I woke up in an unknown forest.</p>\n<p>It seemed like this place was a fantasy world where strange-looking beasts ran rampant. And just like in a game, I seemed to be able to check my enemies’ and my ability.</p>\n<p>Let’s hunt monsters and gather titles in order to level up and evolve into a Greater Dragon!</p>\n<p>And I heard a mysterious voice in my head, “Let’s aim to be the strongest!”</p>",
        "cover": "http://localhost:3222/book/reincarnated-as-a-dragons-egg-lets-aim-to-be-the-strongest/cover/390.webp",
        "color": null,
        "banner": null,


        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 496,
        "status_id": 2,
        "author_id": 46,
        "artist_id": 18,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898040125,
        "slug": "the-tutorial-is-too-hard",
        "title": "The Tutorial Is Too Hard",
        "description": "<p>On a normal boring day, a message appears, inviting him to a Tutorial.</p>\n<p>A tale about Lee Ho Jae and his escape from the Tutorial.</p>\n<p>But he just happened to choose the hardest possible difficulty: Hell…</p>",
        "cover": "http://localhost:3222/book/the-tutorial-is-too-hard/cover/480.webp",
        "color": null,
        "banner": null,


        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 497,
        "status_id": 2,
        "author_id": 47,
        "artist_id": null,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898040743,
        "slug": "beastmaster-of-the-ages",
        "title": "Beastmaster of the Ages",
        "description": "<p>Even in his dreams, Li Tianming can’t stop himself from laughing! Why? Because, his family pets are all the Primordial Chaos Beasts of myth! </p>\n<p>That teeny weeny little chick over there is actually the Aeternal Infernal Phoenix that eats suns! His black cat is the Genesis Chaos Thunderfiend that refines worlds with its lightning. The c*ckroach, well, it’s the Myriad Worlds Deathless Beast that possesses trillions of undying clones… </p>\n<p>Followed by his menagerie of pets, Li Tianming begins his ascension to become the number one beastmaster of the ages. He journeys across the many worlds, only one thing remaining constant. No one is ever ready for the likes of his pets! After all, who’s ever prepared to fight a chicken and its fellows…</p>",
        "cover": "http://localhost:3222/book/beastmaster-of-the-ages/cover/250.webp",
        "color": null,
        "banner": null,


        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 495,
        "status_id": 2,
        "author_id": 15,
        "artist_id": null,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898041378,
        "slug": "the-charm-of-soul-pets",
        "title": "The Charm of Soul Pets",
        "description": "<p>Many islands dotted the vast oceans of this world. However, some of the islands were a lot more sinister than the rest. Those islands, known as Nightmare Islands, were true nightmares to all but the strongest and most fortunate. Children were kidnapped and thrown on these isolated islands by the Nightmare Palace, forced to sign soul pacts with evil soul pets: Nightmares. These devils slowly devoured the souls of their trainers to grow stronger. If the children did not cultivate fast enough, their souls will be devoured whole, leaving only an empty husk behind.</p>\n<p>Chu Mu, the protagonist, was an heir to the Chu Clan, but due to a plotted murder, he was thrown on the island, sentencing him to almost certain death. Dancing on the edge of life and death, he struggled to survive with a small Moonlight Fox he captured. When he finally escaped the devilish foremen on his island, he couldn’t help but let a breath out. But little does he know, the experience was only a beginning to a fated journey with his little Moonlight Fox…</p>",
        "cover": "http://localhost:3222/book/the-charm-of-soul-pets/cover/234.webp",
        "color": null,
        "banner": null,


        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 495,
        "status_id": 2,
        "author_id": 48,
        "artist_id": null,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898042241,
        "slug": "tondemo-skill-de-isekai-hourou",
        "title": "Tondemo Skill de Isekai Hourou Meshi",
        "description": "<p>I, Mukouda Tsuyoshi, was caught up in a summoning circle into a different world where sword and magical skills are the norm.</p>\n<p>However, when the summoners cast ‘Status Appraisal’ on us, the three other people who were summoned with me had [Heroes from Another World] in the occupation box, whereas I was the [Random Guy Caught Up in the Summoning Spell].</p>\n<p>As for our ‘Skill Set’, the three Heroes had outrageous sounding skills rolling after their names like [Holy Sword Technique], [Holy Spear Technique] and [Sacred Magic].</p>\n<p>In fact, I too have a skill you know? My one skill is called… [Net Super]…</p>\n<p>Because it’s clearly not a combat skill, I am automatically treated like garbage.</p>\n<p>Furthermore, the King of the country who had summoned us looked really shady.</p>\n<p>As a veteran lightnovel reader, I can read the atmosphere well enough to come to the conclusion that ‘This is a bad world to be summoned into’.</p>\n<p>Thus, it is decided. No matter what, I must get out of this castle as soon as possible and escape from this rotten country!</p>",
        "cover": "http://localhost:3222/book/tondemo-skill-de-isekai-hourou/cover/842.webp",
        "color": null,
        "banner": null,


        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 496,
        "status_id": 2,
        "author_id": 49,
        "artist_id": 19,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898043182,
        "slug": "the-baby-raising-a-devil",
        "title": "The Baby Raising A Devil",
        "description": "<p>Three regressions, 4th life.</p>\n<p>Although she was prophesied and raised as the child of fate, she was sacrificed when the real child of fate appears.</p>\n<p>‘This country is no good, let’s defect!’</p>\n<p>Leblaine chooses to be adopted to earn money until defecting. There was nothing wrong this far, but the place she chose was a family full of villains. She tried to trick those bad guys in order to live comfortably before defecting…</p>\n<p>“My daughter is the cutest in the world.”</p>\n<p>“Give her the building. She can use it as her bathroom.”</p>\n<p>“It’s okay, Leblaine told me not hit you, but she didn’t say not to kill you?”</p>\n<p>“Who made my sister cry!”</p>\n<p>‘…they’re spiralling out of control, what should I do?’</p>\n<p>***</p>\n<p>“You can’t hit or kill people just because you don’t like them.”</p>\n<p>My family was quiet even though I purposely looked sad.</p>\n<p>‘Then there’s nothing I can do!’</p>\n<p>I looked back at my family with a sharp gaze and said solemnly.</p>\n<p>“I’m going to sleep with a blanket.”</p>\n<p>“I’m wrong, kid!”</p>\n<p>“I’m sorry!”</p>\n<p>“I won’t kill anyone!”</p>\n<p>Good.</p>",
        "cover": "http://localhost:3222/book/the-baby-raising-a-devil/cover/643.webp",
        "color": null,
        "banner": null,


        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 497,
        "status_id": 2,
        "author_id": 50,
        "artist_id": null,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898043971,
        "slug": "age-of-adepts",
        "title": "Age of Adepts",
        "description": "<p>A data loving young man from Earth has an accident which transports him to a dark land filled with terrifying creatures and magical powers. </p>\n<p>Fortunately for him, he has a Biological Assistance Chip to ease his path. </p>\n<p>However, things in this bizarre and strange world are not always as they seem, and, though it is a tremendous asset, the chip doesn’t always work as expected. With all of the crazy creatures and magical mayhem around him, one can only wonder what the future holds for this young man…</p>",
        "cover": "http://localhost:3222/book/age-of-adepts/cover/189.webp",
        "color": null,
        "banner": null,


        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 495,
        "status_id": 2,
        "author_id": 51,
        "artist_id": null,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898044742,
        "slug": "isekai-yururi-kikou-raising-children-while-being-an-adventurer",
        "title": "Isekai Yururi Kikou ~Raising Children While Being an Adventurer~",
        "description": "<p>『I’m terribly sorry…』</p>\n<p>A god was suddenly prostrating in front of Kayano Takumi. He was apparently killed by mistake. Moreover, he can’t be reborn again. However, he is able to live in a different world? Then, let’s do that, please. The god made a mistake again and transferred me into a dangerous forest. Seriously, what’s going on? Besides, there are children here. I can’t leave them here, I will take care of them.</p>",
        "cover": "http://localhost:3222/book/isekai-yururi-kikou-raising-children-while-being-an-adventurer/cover/768.webp",
        "color": null,
        "banner": null,


        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 496,
        "status_id": 2,
        "author_id": 52,
        "artist_id": 20,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898045634,
        "slug": "quick-transmigration-system-male-god-come-here",
        "title": "Quick Transmigration System: Male God, Come Here",
        "description": "<p>After signing the share transfer of the Bai company, Bai Weiwei who had a congenital heart disease got betrayed by her adopted sister she always loved along with her trusted bodyguard.</p>\n<p>Shocked, betrayed, and worried for her father made her unwilling to die, and her resentment actually let her bind with a quick transmigration system. Completing the task means that she will be able to increase the number of days she can live, and she will be able to get revenge on her white lotus sister and the unconscionable bastard bodyguard.</p>\n<p>CEO, Emperor, General… Supreme Immortal? All of them will turn to a love-sick waste who bowed before her skirt.</p>\n<p>Just… why is this unlucky star of a wooden fiancee trying so hard to chase her? Stop sucking my life force already! Our marriage is only for business! I want to break the engagement!</p>\n<p>Ye Yuxuan: “I will never let go of you.”</p>\n<p>Bai Weiwei: “…………..”</p>",
        "cover": "http://localhost:3222/book/quick-transmigration-system-male-god-come-here/cover/214.webp",
        "color": null,
        "banner": null,
        "release_year": null,

        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 495,
        "status_id": 2,
        "author_id": 53,
        "artist_id": null,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898046687,
        "slug": "the-disabled-tyrants-pet-palm-fish-transmigration",
        "title": "The Disabled Tyrant’s Pet Palm Fish [Transmigration]",
        "description": "<p>One day, Li Yu transmigrated into a fish. Furthermore, this fish even had a master. This master was the sinister and terrifying, mute tyrant from a novel. The system gave Li Yu a task. If he wanted to change back into a human, he had to obtain the tyrant’s heart. </p>\n<p>Li Yu full of tears: System, please wake up. I’m only a fish. He can’t even speak. How can we interact?</p>\n<p>System: Stop jabbering. To take down the tyrant, you must attack his heart.</p>\n<p>Li Yu: Can I ask, does the tyrant have a heart–</p>\n<p>Li Yu did his best to blow bubbles at the tyrant, but ended up being captured by the tyrant and raised carefully in a huge, ginormous…… fish tank. The life of a fish was filled with all sorts of blessings.</p>\n<p>Everyday, Mu Tianchi watched the little carp swim around happily, pondering when this fish would finally transform into a human.</p>\n<p>The little carp didn’t know. It’s not that the tyrant had no heart, it’s just that he already gave it away to the little carp that accidentally saved his life.</p>",
        "cover": "http://localhost:3222/book/the-disabled-tyrants-pet-palm-fish-transmigration/cover/201.webp",
        "color": null,
        "banner": null,


        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 495,
        "status_id": 2,
        "author_id": 54,
        "artist_id": null,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898047562,
        "slug": "strategy-to-capture-that-scum-gong",
        "title": "Strategy to Capture that Scum Gong",
        "description": "<p>As a true over-bearing president scum gong, when Xie He for the Nth time rejected his admirer, he heard a sentence in his head: “Congratulations on achieving the “rejects 100 hosts” accomplishment; as an award you will soon bind to the “Scum Gong and Cheap Shou” system, entering other worlds to complete capture missions.</p>\n<p>As a scum gong, Xie He expresses that it is very easy to hide one’s true colors, but… “I Heard My Boyfriend’s Brother Secretly Loves Me,” “Teacher Love Me One More Time,” “Raising Youth Manual,” “Your Majesty, This Servant Obeys,” “The Tyrant Lord’s Substitute Lover,” “Captive of the Empire,” “Disciple’s Cultivation Furnace”…</p>\n<p>Xie He: Wait a minute. These words sound really strange… and why is my role the ‘cheap shou’?</p>\n<p>System: Fighting poison with poison. Using scum to overcome scum. I’ll be relying on you to abuse the scum gong! Remember to not OOC~</p>\n<p>Xie He: Hehe.</p>\n<p>Later…</p>\n<p>Xie He: Hm? You say all the scum gong love me? Sorry, I only love myself.</p>",
        "cover": "http://localhost:3222/book/strategy-to-capture-that-scum-gong/cover/200.webp",
        "color": null,
        "banner": null,


        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 495,
        "status_id": 2,
        "author_id": 55,
        "artist_id": null,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898048405,
        "slug": "immortal-devil-transformation",
        "title": "Immortal Devil Transformation",
        "description": "<p>Sixty Years ago, one middle aged man brought a Qilin that looked like a pug and a mandarin duck that looked exactly like a duck, walking into the Imperial City of the Central Plains for the first time.</p>\n<p>That year, this middle aged man crossed the Mountains and Seas Ridge, passed through the Four Seasons Plain and walked into Qingluan Academy.</p>\n<p>Sixty Years later, Lin Xi sat on an old carriage, starting from Deerwood Village, he passed half the Yun Qin Empire and went straight north, going to Qingluan Academy…</p>\n<p>This is a story involving the honor of an Empire, of loyalty and betrayal, involving youth and hot blood, involving a young man with a different perspective of the world, and a strong cultivating academy.</p>",
        "cover": "http://localhost:3222/book/immortal-devil-transformation/cover/208.webp",
        "color": null,
        "banner": null,


        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 495,
        "status_id": 2,
        "author_id": 56,
        "artist_id": null,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898049296,
        "slug": "the-amber-sword",
        "title": "The Amber Sword",
        "description": "<p>An RPG gamer who played the realistic VRMMORPG ‘The Amber Sword’ for years, finds himself teleported to a parallel world that resembled the game greatly. He takes on the body of an NPC who was fated to die, and with the feelings of the dying NPC and his own heartrending events in the game, he sets out to change the fate of a kingdom that was doomed to tragedy.</p>",
        "cover": "http://localhost:3222/book/the-amber-sword/cover/350.webp",
        "color": null,
        "banner": null,


        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 495,
        "status_id": 2,
        "author_id": 57,
        "artist_id": 21,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898050145,
        "slug": "star-odyssey",
        "title": "Star Odyssey",
        "description": "<p>Join Lu Yin on an epic journey across the Universe, pursuing the truth and tragedy of his past. This is a world of science fantasy where the older generations step back and allow the young to take charge of affairs. Heart-wrenching separations, terrifying situations, all with comic relief that will leave you coming back for more. This is a world where the other characters actually matter, and are revisited frequently as their own lives unfold. Dotting Lu Yin’s path are monumental feats of kingdom-building and treacherous political situations where he must tread carefully if he wants to get to the truth of his history.</p>",
        "cover": "http://localhost:3222/book/star-odyssey/cover/512.webp",
        "color": null,
        "banner": null,
        "release_year": null,

        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 495,
        "status_id": 2,
        "author_id": 58,
        "artist_id": null,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898050783,
        "slug": "tales-of-the-world-devouring-serpent",
        "title": "Tales Of The World Devouring Serpent",
        "description": "<p>Fang Yun has become a snake and got a system, the system requires him to brush up to 10 million reputation values, or face eternal death. So Fang Yun began to crazily upgrade!</p>\n<p>A beautiful outdoor streamer in the mountains, facing the camera and the live friends sending gifts but was caught by a one-meter-long python.</p>\n<p>3,000 meters above the sea surface, Lake Logar is suspected of the appearance of water monsters, causing a large number of tourists to explore.</p>\n<p>On the calm sea, a luxurious cruise ship is slowly moving forward. Visitors stood on the deck as the sea breeze blow. Suddenly, someone found that under the water behind their cruise ship, a black shadow hundred of meters long is following closely.</p>",
        "cover": "http://localhost:3222/book/tales-of-the-world-devouring-serpent/cover/600.webp",
        "color": null,
        "banner": null,
        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 495,
        "status_id": 2,
        "author_id": 59,
        "artist_id": null,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616898051564,
        "slug": "guide-to-raising-the-sick-villain",
        "title": "Guide To Raising the Sick Villain",
        "description": "<p>Qiao Lan transmigrated into a novel.</p>\n<p>She became a cannon-fodder who was rescued by the heroine after being bullied but was jealous of the heroine because of her love for the hero and ultimately ended up miserable.</p>\n<p>When she first entered the novel, Qiao Lan met a cannon fodder more pitiful than her. He was bullied, severely autistic, and had crippled legs.</p>\n<p>Qiao Lan: …</p>\n<p>Thinking of the male partner who had only been able to live for two years, Qiao Lan had a distressed conscience and began to take care of the gloomy boy.</p>\n<p>Tan Mo is the most popular character in a best-selling novel. Fans were dissatisfied with Tan Mo’s bleak ending, so they wrote a fan-made novel featuring Tan Mo. In the book, Tan Mo had crippled legs when he was a child and was bullied. Later, he stood up again and became a powerful businessman.</p>\n<p>Many years ago, Tan Mo was still the gloomy young man who felt inferior because of his body. A classmate laughed behind his back that he was a fool that could not stand. Tan Mo clenched his fingers on the wheelchair until they turned a stark white. Suddenly, a thin girl rushed in from the crowd and punched the laughing boy.</p>\n<p>Later, the girl gently pressed his atrophied legs, Tan Mo’s face turned pale, “Don’t look, it’s ugly.”</p>\n<p>Qiao Lan looked carefully, “It’s not ugly at all.”</p>\n<p>“Will you always stay with me?”</p>\n<p>“I will.”</p>\n<p>Tan Mo clasped her waist fiercely, “Then never leave me.”</p>\n<p>Qiao Lan nodded because Tan Mo only stayed alive for another two years.</p>\n<p>Two years later, Qiao Lan was hugged tightly by Tan Mo who was struggling to stand up. At that time, Qiao Lan realized that there seemed to be something wrong. She seemed to have transmigrated into the wrong book.</p>",
        "cover": "http://localhost:3222/book/guide-to-raising-the-sick-villain/cover/245.webp",
        "color": null,
        "banner": null,


        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2445,
        "language_id": 495,
        "status_id": 2,
        "author_id": 60,
        "artist_id": null,
        "words": 0,
        "is_original": 0,
        "is_adult": null,
        "is_comic": 0,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      },
      {
        "id": 1616974654831,
        "slug": "solo-leveling",
        "title": "Solo Leveling",
        "description": "Dez anos atrás, depois do \"Portal\" que conecta o mundo real com um mundo de monstros se abriu, algumas pessoas comuns receberam o poder de caçar os monstros do portal. Eles são conhecidos como caçadores. Porém, nem todos os caçadores são fortes. Meu nome é Sung Jin-Woo, um caçador de rank E. Eu sou alguém que tem que arriscar a própria vida nas dungeons mais fracas, \"O mais fraco do mundo\". Sem ter nenhuma habilidade à disposição, eu mal consigo dinheiro nas dungeons de baixo nível... Ao menos até eu encontrar uma dungeon escondida com a maior dificuldade dentro do Rank D! No fim, enquanto aceitava minha morte, eu ganhei um novo poder...",
        "cover": "http://localhost:3222/book/solo-leveling/cover/undefined.webp",
        "color": null,
        "banner": null,
        "release_year": null,

        "chapters": 8,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2100,
        "language_id": 400,
        "status_id": 2,
        "author_id": 61,
        "artist_id": null,
        "words": 0,
        "is_original": 0,
        "is_adult": 0,
        "is_comic": 1,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,
      },
      {
        "id": 1616977089739,
        "slug": "maou-sama-to-kekkon-shitai",
        "title": "Maou-sama To Kekkon Shitai",
        "description": "Um dia, a rainha demônio salva Haru, um garoto humano que estava prestes a ser vendido como um escravo, e o traz de volta como seu atendente. Anos depois, a entediada rainha demônio pergunta para um crescido Haru o que mais ela pode fazer. Se casar, Haru responde. E então, uma comedia romântica de fazer o coração bater mais rápido começa entre um demônio inocente e seu servo.",
        "cover": "http://localhost:3222/book/maou-sama-to-kekkon-shitai/cover/undefined.webp",
        "color": null,
        "banner": null,
        "release_year": null,

        "chapters": 0,
        "target_audience": "0",
        "last_chapter_id": null,
        "type_id": 2100,
        "language_id": 400,
        "status_id": 2,
        "author_id": 71,
        "artist_id": null,
        "words": 0,
        "is_original": 0,
        "is_adult": 0,
        "is_comic": 1,
        "is_visible": 1,
        "free_edition": 1,
        "is_pay": 1,


      }
    ])
  }
}
